partner_location_update:
  cron: "* * * * *"
  class: "PartnerLocationUpdateWorker"
  queue: partner

# sample:
#   cron: "*/30 * * * *"
#   class: "HardWorker"
#   queue: hard_worker_long
#   args:
#     hard: "stuff"